/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.EquipmentDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Equipment;

/**
 *
 * @author HP
 */
public class AvailableForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AvailableForm
     */
    // Table model for equipment data
    private DefaultTableModel tableModel;
    
    public AvailableForm() {
        initComponents();
        this.setSize(992, 771);
        
        // Setup table columns
        setupTableModel();
        
        // Load all equipment data
        loadAllEquipment();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EquipmentTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        SearchTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Available");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        EquipmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(EquipmentTable);

        jLabel9.setText("__________________________________________________________________________________________________________");

        SearchBtn.setBackground(new java.awt.Color(0, 102, 102));
        SearchBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N
        SearchBtn.setText("Search Equipment");
        SearchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Available Equipments");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBtn))))
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        performSearch();
    }//GEN-LAST:event_SearchBtnActionPerformed
    
    private void SearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtActionPerformed
        performSearch();
    }//GEN-LAST:event_SearchTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EquipmentTable;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Setup the table model with appropriate columns
     */
    private void setupTableModel() {
        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table cells non-editable
            }
        };
        
        // Define columns
        tableModel.addColumn("ID");
        tableModel.addColumn("Equipment Name");
        tableModel.addColumn("Category");
        tableModel.addColumn("Description");
        tableModel.addColumn("Condition");
        tableModel.addColumn("Status");
        
        // Set the table model
        EquipmentTable.setModel(tableModel);
        
        // Adjust column widths
        EquipmentTable.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
        EquipmentTable.getColumnModel().getColumn(1).setPreferredWidth(150); // Name
        EquipmentTable.getColumnModel().getColumn(2).setPreferredWidth(100); // Category
        EquipmentTable.getColumnModel().getColumn(3).setPreferredWidth(200); // Description
        EquipmentTable.getColumnModel().getColumn(4).setPreferredWidth(100); // Condition
        EquipmentTable.getColumnModel().getColumn(5).setPreferredWidth(100); // Status
    }
    
    /**
     * Load all equipment data into the table
     */
    private void loadAllEquipment() {
        EquipmentDao equipmentDao = new EquipmentDao();
        List<Equipment> equipmentList = equipmentDao.findAllEquipment();
        
        // Clear existing data
        tableModel.setRowCount(0);
        
        // Populate table with equipment data
        for (Equipment equipment : equipmentList) {
            Object[] rowData = {
                equipment.getEquipmentId(),
                equipment.getEquipmentName(),
                equipment.getCategoryName(),
                equipment.getDescription(),
                equipment.getCondition(),
                equipment.getStatus()
            };
            tableModel.addRow(rowData);
        }
    }
    
    /**
     * Perform search based on the search text field
     */
    private void performSearch() {
        String searchText = SearchTxt.getText().trim();
        
        if (searchText.isEmpty()) {
            // If search field is empty, load all equipment
            loadAllEquipment();
        } else {
            // Search for equipment by name
            searchEquipment(searchText);
        }
    }
    
    /**
     * Search equipment by name
     * @param searchText The text to search for
     */
    private void searchEquipment(String searchText) {
        EquipmentDao equipmentDao = new EquipmentDao();
        List<Equipment> searchResults = equipmentDao.searchEquipmentByName(searchText);
        
        // Clear existing data
        tableModel.setRowCount(0);
        
        // Populate table with search results
        for (Equipment equipment : searchResults) {
            Object[] rowData = {
                equipment.getEquipmentId(),
                equipment.getEquipmentName(),
                equipment.getCategoryName(),
                equipment.getDescription(),
                equipment.getCondition(),
                equipment.getStatus()
            };
            tableModel.addRow(rowData);
        }
    }
}
