package view;

import dao.BorrowDao;
import dao.EquipmentDao;
import dao.UserDao;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Borrow;
import model.Equipment;
import model.User;

/**
 *
 * @author HP
 */
public class BorrowForm extends javax.swing.JInternalFrame {

    private BorrowDao borrowDao;
    private EquipmentDao equipmentDao;
    private User currentUser;
    private List<Equipment> equipmentList;
    
    
    public BorrowForm() {
        initComponents();
        this.setSize(992, 771);
        
        // Initialize DAOs
        borrowDao = new BorrowDao();
        equipmentDao = new EquipmentDao();
                        
        // Load data
        loadCurrentUser();
        loadEquipmentDropdown();
        setupEquipmentListener();
    }
    
    // Version that accepts a user parameter (for use when launched from dashboard)
    public BorrowForm(User user) {
        this(); // Call default constructor
        this.currentUser = user;
        loadBorrowerDropdown(); // Reload with the provided user
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Equipment = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BorrowerBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        EquipmentBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        BorrowDateField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        ReturnDateField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        StatusBox = new javax.swing.JComboBox<>();
        ConfirmBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        EquipmentIDBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(801, 0));

        Equipment.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/circle.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel2.setText("Borrower:");

        BorrowerBox.setEditable(true);
        BorrowerBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Equipment:");

        EquipmentBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Borrow Date:");

        try {
            BorrowDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        BorrowDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowDateFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Return Date:");

        try {
            ReturnDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Status:");

        StatusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ConfirmBtn.setBackground(new java.awt.Color(0, 153, 153));
        ConfirmBtn.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        ConfirmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Check Mark.png"))); // NOI18N
        ConfirmBtn.setText("Confirm Borrowing");
        ConfirmBtn.setToolTipText("Borrow");
        ConfirmBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Equipment ID:");

        EquipmentIDBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setText("Date format should be 2025-09-05");

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setText("Date format should be 2025-09-05");

        javax.swing.GroupLayout EquipmentLayout = new javax.swing.GroupLayout(Equipment);
        Equipment.setLayout(EquipmentLayout);
        EquipmentLayout.setHorizontalGroup(
            EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquipmentLayout.createSequentialGroup()
                .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EquipmentLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(StatusBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BorrowDateField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EquipmentBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BorrowerBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EquipmentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(EquipmentIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(EquipmentLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EquipmentLayout.setVerticalGroup(
            EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquipmentLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(BorrowerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipmentBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipmentIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorrowDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(EquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Equipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Equipment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed
        // Validate form fields
        if (validateFields()) {
            // Get selected equipment
            String equipmentName = EquipmentBox.getSelectedItem().toString();
            int equipmentId = Integer.parseInt(EquipmentIDBox.getSelectedItem().toString());
            
            // Check if equipment is available
            if (borrowDao.isEquipmentAvailable(equipmentId)) {
                try {
                    // Parse dates
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    java.util.Date borrowUtilDate = sdf.parse(BorrowDateField.getText().trim());
                    java.util.Date returnUtilDate = sdf.parse(ReturnDateField.getText().trim());
                    
                    // Convert to SQL Date
                    Date borrowDate = new Date(borrowUtilDate.getTime());
                    Date returnDate = new Date(returnUtilDate.getTime());
                    
                    // Create borrow record
                    Borrow borrow = new Borrow();
                    borrow.setUserId(currentUser.getUserId());
                    borrow.setEquipmentId(equipmentId);
                    borrow.setBorrowDate(borrowDate);
                    borrow.setReturnDate(returnDate);
                    borrow.setStatus("Borrowed");
                    
                    // Save to database
                    int result = borrowDao.createBorrow(borrow);
                    
                    if (result > 0) {
                        JOptionPane.showMessageDialog(this, 
                                "Equipment successfully borrowed!", 
                                "Success", JOptionPane.INFORMATION_MESSAGE);
                        clearForm();
                        loadEquipmentDropdown(); // Reload equipment to update availability
                    } else {
                        JOptionPane.showMessageDialog(this, 
                                "Failed to borrow equipment.", 
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(this, 
                            "Invalid date format. Please use YYYY-MM-DD.", 
                            "Date Format Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, 
                        "This equipment is currently unavailable for borrowing.", 
                        "Equipment Unavailable", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_ConfirmBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        clearForm();
        this.dispose(); // Close the form
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void BorrowDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowDateFieldActionPerformed
        // Not needed for now
    }//GEN-LAST:event_BorrowDateFieldActionPerformed

    /**
     * Load current user from session (if available)
     * For now, we'll use a hardcoded method to simulate user login
     */
    private void loadCurrentUser() {
        // For testing, you can use a hardcoded email. In a real app, this would come from login session.
        String userEmail = "fabrice@user.com"; // Simulated logged-in user
        
        // Get user details from database
        currentUser = borrowDao.getUserByEmail(userEmail);
        
        // Load borrower dropdown with the current user
        loadBorrowerDropdown();
    }
    
    /**
     * Load borrower dropdown with the current user only
     */
    private void loadBorrowerDropdown() {
        DefaultComboBoxModel<String> borrowerModel = new DefaultComboBoxModel<>();
        
        if (currentUser != null) {
            borrowerModel.addElement(currentUser.getFullName() + " (" + currentUser.getEmail() + ")");
        }
        
        BorrowerBox.setModel(borrowerModel);
        BorrowerBox.setEnabled(false); // Make it non-editable since there's only one option
    }
    
    /**
     * Load equipment dropdown with all equipment
     */
    private void loadEquipmentDropdown() {
        DefaultComboBoxModel<String> equipmentModel = new DefaultComboBoxModel<>();
        
        // Get all equipment
        equipmentList = borrowDao.getAllEquipment();
        
        for (Equipment equipment : equipmentList) {
            equipmentModel.addElement(equipment.getEquipmentName() + " (" + equipment.getStatus() + ")");
        }
        
        EquipmentBox.setModel(equipmentModel);
    }
    
    /**
     * Set up listener for equipment dropdown
     */
    private void setupEquipmentListener() {
        EquipmentBox.addActionListener((e) -> {
            int selectedIndex = EquipmentBox.getSelectedIndex();
            if (selectedIndex >= 0 && selectedIndex < equipmentList.size()) {
                // Get selected equipment
                Equipment selected = equipmentList.get(selectedIndex);
                
                // Update equipment ID field
                DefaultComboBoxModel<String> idModel = new DefaultComboBoxModel<>();
                idModel.addElement(String.valueOf(selected.getEquipmentId()));
                EquipmentIDBox.setModel(idModel);
                
                // Update status field
                DefaultComboBoxModel<String> statusModel = new DefaultComboBoxModel<>();
                statusModel.addElement(selected.getStatus());
                StatusBox.setModel(statusModel);
                
                // Set the background color based on availability
                if ("Available".equals(selected.getStatus())) {
                    StatusBox.setBackground(new java.awt.Color(0, 204, 102)); // Green for available
                } else {
                    StatusBox.setBackground(new java.awt.Color(255, 102, 102)); // Red for unavailable
                }
            }
        });
    }
    
    /**
     * Validate form fields before submission
     * @return true if all fields are valid, false otherwise
     */
    private boolean validateFields() {
        // Check borrower
        if (BorrowerBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a borrower", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // Check equipment
        if (EquipmentBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select equipment", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // Check borrow date
        String borrowDate = BorrowDateField.getText().trim();
        if (borrowDate.isEmpty() || borrowDate.length() != 10) {
            JOptionPane.showMessageDialog(this, "Please enter a valid borrow date (YYYY-MM-DD)", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // Check return date
        String returnDate = ReturnDateField.getText().trim();
        if (returnDate.isEmpty() || returnDate.length() != 10) {
            JOptionPane.showMessageDialog(this, "Please enter a valid return date (YYYY-MM-DD)", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // Check status
        String status = StatusBox.getSelectedItem().toString();
        if (!status.contains("Available")) {
            JOptionPane.showMessageDialog(this, "This equipment is not available for borrowing.", "Equipment Unavailable", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // Validate date format and logic
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date borrowUtilDate = sdf.parse(borrowDate);
            java.util.Date returnUtilDate = sdf.parse(returnDate);
            
            // Check if return date is after borrow date
            if (returnUtilDate.before(borrowUtilDate)) {
                JOptionPane.showMessageDialog(this, "Return date must be after borrow date", "Date Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD.", "Date Format Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    /**
     * Clear form fields
     */
    private void clearForm() {
        BorrowDateField.setText("");
        ReturnDateField.setText("");
        loadEquipmentDropdown(); // Reload equipment options
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField BorrowDateField;
    private javax.swing.JComboBox<String> BorrowerBox;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JPanel Equipment;
    private javax.swing.JComboBox<String> EquipmentBox;
    private javax.swing.JComboBox<String> EquipmentIDBox;
    private javax.swing.JFormattedTextField ReturnDateField;
    private javax.swing.JComboBox<String> StatusBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
