/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.EquipmentCategoryDao;
import dao.EquipmentDao;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Equipment;
import model.EquipmentCategory;

/**
 *
 * @author HP
 */
public class HandleItemForm extends javax.swing.JInternalFrame {
    
    private DefaultTableModel tableModel;
    private EquipmentDao equipmentDao;
    private EquipmentCategoryDao categoryDao;

    /**
     * Creates new form HandleItemForm
     */
    public HandleItemForm() {
        initComponents();
        
        // Initialize DAOs
        equipmentDao = new EquipmentDao();
        categoryDao = new EquipmentCategoryDao();
        
        // Set up table model
        setupTableModel();
        
        // Load data from database
        loadCategoriesIntoComboBox();
        loadStatusOptions();
        loadEquipmentData();
        
        // Set up table row selection listener
        setupTableSelectionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EquipmentIdField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ConditionFiels = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EquipmentNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DescriptionField = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        EquipemntTable = new javax.swing.JTable();
        CategoryNameBox = new javax.swing.JComboBox<>();

        setTitle("Handling Equipment");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Handle1.png"))); // NOI18N
        jLabel1.setText("EQUIPMENTS HANDLING.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Equipment Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Equipment ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Condition:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Description:");

        SaveBtn.setBackground(new java.awt.Color(0, 153, 153));
        SaveBtn.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Handle.png"))); // NOI18N
        SaveBtn.setText("SAVE ");
        SaveBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setBackground(new java.awt.Color(0, 153, 153));
        UpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        UpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        UpdateBtn.setText("UPDATE");
        UpdateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("________________________________________________________________________________________");

        DeleteBtn.setBackground(new java.awt.Color(0, 153, 153));
        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        DeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        DeleteBtn.setText("DELETE");
        DeleteBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EquipemntTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(EquipemntTable);

        CategoryNameBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ConditionFiels)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CategoryNameBox, 0, 280, Short.MAX_VALUE)
                            .addComponent(EquipmentNameField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(EquipmentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EquipmentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EquipmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(CategoryNameBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConditionFiels, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // Validate form fields
        if (validateFormFields()) {
            // Create equipment object from form data
            Equipment equipment = new Equipment();
            equipment.setEquipmentName(EquipmentNameField.getText().trim());
            
            // Get category ID from selected category name
            String selectedCategory = CategoryNameBox.getSelectedItem().toString();
            int categoryId = categoryDao.getCategoryIdByName(selectedCategory);
            equipment.setCategoryId(categoryId);
            
            equipment.setDescription(DescriptionField.getText().trim());
            equipment.setCondition(ConditionFiels.getText().trim());
            equipment.setStatus(jComboBox1.getSelectedItem().toString());
            
            // Save to database
            int result = equipmentDao.createEquipment(equipment);
            
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Equipment saved successfully!");
                clearForm();
                loadEquipmentData();  // Refresh table data
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save equipment.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // Check if an equipment is selected
        if (EquipmentIdField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an equipment to update.", 
                                         "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validate form fields
        if (validateFormFields()) {
            // Create equipment object from form data
            Equipment equipment = new Equipment();
            equipment.setEquipmentId(Integer.parseInt(EquipmentIdField.getText().trim()));
            equipment.setEquipmentName(EquipmentNameField.getText().trim());
            
            // Get category ID from selected category name
            String selectedCategory = CategoryNameBox.getSelectedItem().toString();
            int categoryId = categoryDao.getCategoryIdByName(selectedCategory);
            equipment.setCategoryId(categoryId);
            
            equipment.setDescription(DescriptionField.getText().trim());
            equipment.setCondition(ConditionFiels.getText().trim());
            equipment.setStatus(jComboBox1.getSelectedItem().toString());
            
            // Update in database
            int result = equipmentDao.updateEquipment(equipment);
            
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Equipment updated successfully!");
                loadEquipmentData();  // Refresh table data
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update equipment.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // Check if an equipment is selected
        if (EquipmentIdField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an equipment to delete.", 
                                         "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete this record?", 
                "Confirm Deletion", 
                JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.WARNING_MESSAGE);
        
        if (confirm == JOptionPane.OK_OPTION) {
            int equipmentId = Integer.parseInt(EquipmentIdField.getText().trim());
            
            // Delete from database
            int result = equipmentDao.deleteEquipment(equipmentId);
            
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Equipment deleted successfully!");
                clearForm();
                loadEquipmentData();  // Refresh table data
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete equipment.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    /**
     * Set up the table model with column headers
     */
    private void setupTableModel() {
        tableModel = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Equipment Name", "Category", "Description", "Condition", "Status"}
        ) {
            // Make cells non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        EquipemntTable.setModel(tableModel);
    }
    
    /**
     * Load equipment data from database into the table
     */
    private void loadEquipmentData() {
        // Clear existing table data
        tableModel.setRowCount(0);
        
        // Get equipment list from database
        List<Equipment> equipmentList = equipmentDao.findAllEquipment();
        
        // Populate table with equipment data
        for (Equipment equipment : equipmentList) {
            tableModel.addRow(new Object[] {
                equipment.getEquipmentId(),
                equipment.getEquipmentName(),
                equipment.getCategoryName(),
                equipment.getDescription(),
                equipment.getCondition(),
                equipment.getStatus()
            });
        }
    }
    
    /**
     * Load categories into the category combo box
     */
    private void loadCategoriesIntoComboBox() {
        List<EquipmentCategory> categories = categoryDao.getAllCategories();
        DefaultComboBoxModel<String> categoryModel = new DefaultComboBoxModel<>();
        
        for (EquipmentCategory category : categories) {
            categoryModel.addElement(category.getCategoryName());
        }
        
        CategoryNameBox.setModel(categoryModel);
    }
    
    /**
     * Load status options into the status combo box
     */
    private void loadStatusOptions() {
        String[] statuses = equipmentDao.getEquipmentStatuses();
        DefaultComboBoxModel<String> statusModel = new DefaultComboBoxModel<>(statuses);
        jComboBox1.setModel(statusModel);
    }
    
    /**
     * Set up listener for table row selection
     */
    private void setupTableSelectionListener() {
        EquipemntTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = EquipemntTable.getSelectedRow();
                if (selectedRow >= 0) {
                    // Get data from selected row
                    int equipmentId = (int) tableModel.getValueAt(selectedRow, 0);
                    String equipmentName = (String) tableModel.getValueAt(selectedRow, 1);
                    String categoryName = (String) tableModel.getValueAt(selectedRow, 2);
                    String description = (String) tableModel.getValueAt(selectedRow, 3);
                    String condition = (String) tableModel.getValueAt(selectedRow, 4);
                    String status = (String) tableModel.getValueAt(selectedRow, 5);
                    
                    // Populate form fields
                    EquipmentIdField.setText(String.valueOf(equipmentId));
                    EquipmentNameField.setText(equipmentName);
                    CategoryNameBox.setSelectedItem(categoryName);
                    DescriptionField.setText(description);
                    ConditionFiels.setText(condition);
                    jComboBox1.setSelectedItem(status);
                }
            }
        });
    }
    
    /**
     * Validate form fields
     * @return true if all required fields are filled, false otherwise
     */
    private boolean validateFormFields() {
        if (EquipmentNameField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Equipment name is required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            EquipmentNameField.requestFocus();
            return false;
        }
        
        if (CategoryNameBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a category!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            CategoryNameBox.requestFocus();
            return false;
        }
        
        if (ConditionFiels.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Condition is required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            ConditionFiels.requestFocus();
            return false;
        }
        
        if (jComboBox1.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a status!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            jComboBox1.requestFocus();
            return false;
        }
        
        return true;
    }
    
    /**
     * Clear form fields
     */
    private void clearForm() {
        EquipmentIdField.setText("");
        EquipmentNameField.setText("");
        CategoryNameBox.setSelectedIndex(0);  // Select first item
        DescriptionField.setText("");
        ConditionFiels.setText("");
        jComboBox1.setSelectedIndex(0);  // Select first item
        EquipemntTable.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CategoryNameBox;
    private javax.swing.JTextField ConditionFiels;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JTable EquipemntTable;
    private javax.swing.JTextField EquipmentIdField;
    private javax.swing.JTextField EquipmentNameField;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
