package view;

import dao.BorrowDao;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import model.Borrow;

/**
 *
 * @author HP
 */
public class ReturnForm extends javax.swing.JInternalFrame {

    private BorrowDao borrowDao;
    private Map<String, Integer> borrowIdMap;
    private SimpleDateFormat dateFormatter;
    
    /**
     * Creates new form Return
     */
    public ReturnForm() {
        initComponents();
        this.setSize(992, 771);
        
        // Initialize DAO and formatter
        borrowDao = new BorrowDao();
        borrowIdMap = new HashMap<>();
        dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
        
        // Run diagnostics
        runDiagnostics();
        
        // Load borrow IDs into combo box
        loadBorrowIds();
        
        // Add action listener to combo box
        SelectBorrowBox.addActionListener(evt -> borrowIdSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SelectBorrowBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EquipmentNameField = new javax.swing.JTextField();
        BorrowNameField = new javax.swing.JTextField();
        BorrowDateField = new javax.swing.JTextField();
        ReturnDateField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ActuaReturnlDateField = new javax.swing.JTextField();
        ConfirmBtn = new javax.swing.JButton();

        setTitle("Return");
        setPreferredSize(new java.awt.Dimension(831, 715));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Kit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Return An Item");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Select Borrow ID:");

        SelectBorrowBox.setEditable(true);
        SelectBorrowBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("__________________________________________________________________________________________________");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Borrower Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Equipment Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Borrow Date:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Expected Return Date:");

        EquipmentNameField.setEditable(false);

        BorrowNameField.setEditable(false);

        BorrowDateField.setEditable(false);

        ReturnDateField.setEditable(false);

        jLabel9.setText("____________________________________________________________________________________________________");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Actual Return Date:");

        ConfirmBtn.setBackground(new java.awt.Color(0, 153, 153));
        ConfirmBtn.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        ConfirmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/return1.png"))); // NOI18N
        ConfirmBtn.setText("Confirm Return");
        ConfirmBtn.setToolTipText("Borrow");
        ConfirmBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BorrowNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EquipmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BorrowDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(ReturnDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel3)
                        .addGap(92, 92, 92)
                        .addComponent(SelectBorrowBox, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(ActuaReturnlDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SelectBorrowBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BorrowNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(EquipmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BorrowDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ReturnDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ActuaReturnlDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ConfirmBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed
        // Get selected borrow ID
        String selectedItem = (String) SelectBorrowBox.getSelectedItem();
        if (selectedItem == null || selectedItem.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a borrow ID", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get actual return date for logging purposes
        String actualReturnDateText = ActuaReturnlDateField.getText().trim();
        if (actualReturnDateText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the actual return date", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Parse return date (we'll keep this for future use when the database is updated)
        Date actualReturnDate;
        try {
            java.util.Date parsedDate = dateFormatter.parse(actualReturnDateText);
            actualReturnDate = new Date(parsedDate.getTime());
            
            // Validate date is not in the future
            java.util.Date today = new java.util.Date();
            if (parsedDate.after(today)) {
                JOptionPane.showMessageDialog(this, "Return date cannot be in the future", 
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get borrow ID from selected item
        Integer borrowId = borrowIdMap.get(selectedItem);
        if (borrowId == null) {
            JOptionPane.showMessageDialog(this, "Invalid borrow selection", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Confirm return
        boolean success = borrowDao.returnEquipment(borrowId, actualReturnDate);
        if (success) {
            JOptionPane.showMessageDialog(this, "Equipment returned successfully!\n" +
                    "Return Date: " + actualReturnDateText,
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            clearForm();
            loadBorrowIds(); // Reload borrow IDs as this one is no longer active
        } else {
            JOptionPane.showMessageDialog(this, "Failed to return equipment. Please try again.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ConfirmBtnActionPerformed
    
    /**
     * Load active borrow IDs into the combo box
     */
    private void loadBorrowIds() {
        // Clear the combo box and map
        SelectBorrowBox.removeAllItems();
        borrowIdMap.clear();
        
        // Add empty item
        SelectBorrowBox.addItem("");
        
        try {
            // Get borrow IDs from database
            Map<Integer, String> borrowMap = borrowDao.getBorrowIdDisplayMap();
            
            // Check if we got any results
            if (borrowMap.isEmpty()) {
                System.out.println("No rented equipment found in the database");
                // Show message to user
                JOptionPane.showMessageDialog(this, 
                        "No rented equipment found in the database.\n" +
                        "You must borrow equipment first before returning it.", 
                        "No Borrowed Equipment", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            // Add items to combo box
            for (Map.Entry<Integer, String> entry : borrowMap.entrySet()) {
                String displayText = entry.getValue();
                SelectBorrowBox.addItem(displayText);
                borrowIdMap.put(displayText, entry.getKey());
            }
            
            System.out.println("Loaded " + borrowMap.size() + " borrowed items");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                    "Error loading borrowed equipment: " + e.getMessage(), 
                    "Loading Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Handle borrow ID selection
     */
    private void borrowIdSelected() {
        // Get selected item
        String selectedItem = (String) SelectBorrowBox.getSelectedItem();
        
        // Clear form fields if empty selection
        if (selectedItem == null || selectedItem.isEmpty()) {
            clearFormFields();
            return;
        }
        
        // Get borrow ID from selected item
        Integer borrowId = borrowIdMap.get(selectedItem);
        if (borrowId == null) {
            clearFormFields();
            return;
        }
        
        // Get borrow details from database
        Borrow borrow = borrowDao.getBorrowById(borrowId);
        if (borrow != null) {
            // Populate form fields
            BorrowNameField.setText(borrow.getUserName());
            EquipmentNameField.setText(borrow.getEquipmentName());
            BorrowDateField.setText(dateFormatter.format(borrow.getBorrowDate()));
            ReturnDateField.setText(dateFormatter.format(borrow.getReturnDate()));
            
            // Set today's date as default return date
            ActuaReturnlDateField.setText(dateFormatter.format(java.sql.Date.valueOf(LocalDate.now())));
        }
    }
    
    /**
     * Clear all form fields
     */
    private void clearForm() {
        SelectBorrowBox.setSelectedIndex(0);
        clearFormFields();
    }
    
    /**
     * Clear all form fields except borrow ID
     */
    private void clearFormFields() {
        BorrowNameField.setText("");
        EquipmentNameField.setText("");
        BorrowDateField.setText("");
        ReturnDateField.setText("");
        ActuaReturnlDateField.setText("");
    }
    
    /**
     * Run diagnostics to check for rented equipment and borrow records
     */
    private void runDiagnostics() {
        System.out.println("=== RETURN FORM DIAGNOSTICS ===");
        
        // Check database structure to identify correct column names
        System.out.println("Checking database structure...");
        borrowDao.checkBorrowingTableStructure();
        
        // Check for rented equipment
        List<String> rentedItems = borrowDao.checkRentedEquipment();
        System.out.println("Found " + rentedItems.size() + " rented equipment items:");
        for (String item : rentedItems) {
            System.out.println(" - " + item);
        }
        
        // Check for borrowing records
        int recordCount = borrowDao.checkBorrowRecords();
        System.out.println("Found " + recordCount + " borrowing records in the database");
        
        // If we have rented equipment but no borrow records, create test data
        if (!rentedItems.isEmpty() && recordCount == 0) {
            System.out.println("Creating test borrow records for rented equipment...");
            borrowDao.insertTestBorrowData();
            
            // Check again after creating test data
            recordCount = borrowDao.checkBorrowRecords();
            System.out.println("Now have " + recordCount + " borrowing records in the database");
            
            // Check structure again after creating records
            borrowDao.checkBorrowingTableStructure();
        }
        
        System.out.println("==============================");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActuaReturnlDateField;
    private javax.swing.JTextField BorrowDateField;
    private javax.swing.JTextField BorrowNameField;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JTextField EquipmentNameField;
    private javax.swing.JTextField ReturnDateField;
    private javax.swing.JComboBox<String> SelectBorrowBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
