/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.UserDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.User;

/**
 *
 * @author HP
 */
public class UsersForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsersForm
     */
    // Table model for user data
    private DefaultTableModel tableModel;
    
    public UsersForm() {
        initComponents();
        this.setSize(992, 771);
        
        // Setup table columns
        setupTableModel();
        
        // Load all user data
        loadAllUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SearchTxt1 = new javax.swing.JTextField();
        SearchTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxt1ActionPerformed(evt);
            }
        });
        SearchBtn1 = new javax.swing.JButton();

        setTitle("Users");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User Male.png"))); // NOI18N
        jLabel1.setText("Users");

        SearchBtn1.setBackground(new java.awt.Color(0, 102, 102));
        SearchBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchBtn1.setText("Search ");
        SearchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(SearchTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(SearchBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtn1ActionPerformed
        performSearch();
    }//GEN-LAST:event_SearchBtn1ActionPerformed
    
    private void SearchTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxt1ActionPerformed
        performSearch();
    }//GEN-LAST:event_SearchTxt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchBtn1;
    private javax.swing.JTextField SearchTxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Setup the table model with appropriate columns
     */
    private void setupTableModel() {
        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table cells non-editable
            }
        };
        
        // Define columns
        tableModel.addColumn("ID");
        tableModel.addColumn("Full Name");
        tableModel.addColumn("Email");
        tableModel.addColumn("Admin");
        
        // Set the table model
        jTable1.setModel(tableModel);
        
        // Adjust column widths
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);   // ID
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);  // Full Name
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);  // Email
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);   // Admin
    }
    
    /**
     * Load all users into the table
     */
    private void loadAllUsers() {
        UserDao userDao = new UserDao();
        List<User> userList = userDao.findAllUsers();
        
        // Clear existing data
        tableModel.setRowCount(0);
        
        // Populate table with user data
        for (User user : userList) {
            Object[] rowData = {
                user.getUserId(),
                user.getFullName(),
                user.getEmail(),
                user.isAdmin() ? "Yes" : "No"
            };
            tableModel.addRow(rowData);
        }
    }
    
    /**
     * Perform search based on the search text field
     */
    private void performSearch() {
        String searchText = SearchTxt1.getText().trim();
        
        if (searchText.isEmpty()) {
            // If search field is empty, load all users
            loadAllUsers();
        } else {
            // Search for users by name
            searchUsers(searchText);
        }
    }
    
    /**
     * Search users by name
     * @param searchText The text to search for
     */
    private void searchUsers(String searchText) {
        UserDao userDao = new UserDao();
        List<User> searchResults = userDao.searchUsersByName(searchText);
        
        // Clear existing data
        tableModel.setRowCount(0);
        
        // Populate table with search results
        for (User user : searchResults) {
            Object[] rowData = {
                user.getUserId(),
                user.getFullName(),
                user.getEmail(),
                user.isAdmin() ? "Yes" : "No"
            };
            tableModel.addRow(rowData);
        }
    }
}
